// <auto-generated />
using System;
using Dunder.Mifflin.Api.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dunder.Mifflin.Api.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20231014165727_SplitQuotesAndLines")]
    partial class SplitQuotesAndLines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Dunder.Mifflin.Api.Entities.LineDbEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineText")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("QuoteDbEntityId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Scene")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Speaker")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuoteDbEntityId");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("Dunder.Mifflin.Api.Entities.QuoteDbEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quote")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Speaker")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("Dunder.Mifflin.Api.Entities.LineDbEntity", b =>
                {
                    b.HasOne("Dunder.Mifflin.Api.Entities.QuoteDbEntity", null)
                        .WithMany("Lines")
                        .HasForeignKey("QuoteDbEntityId");
                });

            modelBuilder.Entity("Dunder.Mifflin.Api.Entities.QuoteDbEntity", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
